### ISSUE TITLE
Performance and Current Streams not updating.

### ISSUE THREAD

**Issue by leddie24** [nwithan8/tauticord#140]
Docker compose file (with some stuff ***'d out)

My Performance and Plex Stream stats (namely Current Streams) is not updating. Turned off my plex and waited 15+ minutes and it still said Current Streams: 1

 ```
GNU nano 6.2                                                    docker-compose.yml *                                                            version: "3.9"
services:
  tauticord:
    image: nwithan8/tauticord:latest
    volumes:
      - ./config:/config
      - ./logs:/logs
    environment:
      TC_DISCORD_BOT_TOKEN: **********
      TC_DISCORD_SERVER_ID: ******
      TC_TAUTULLI_KEY: *****
      TC_TAUTULLI_URL: ****
      TC_USE_SELF_SIGNED_CERT: "False"
      TC_REFRESH_SECONDS: 15
      TC_TERMINATE_MESSAGE: "Your stream has ended."
      TC_SERVER_NAME: "******"
      TC_USE_24_HOUR_TIME: "False"
      TC_HIDE_USERNAMES: "True"
      TC_HIDE_PLATFORMS: "False"
      TC_HIDE_PLAYER_NAMES: "False"
      TC_HIDE_QUALITY: "False"
      TC_HIDE_BANDWIDTH: "False"
      TC_HIDE_TRANSCODE: "False"
      TC_HIDE_PROGRESS: "False"
      TC_HIDE_ETA: "False"
      TC_USE_FRIENDLY_NAMES: "False"
      TC_THOUSANDS_SEPARATOR: ""
      TC_VC_STATS_CATEGORY_NAME: "Plex Stream Stats"
      TC_VC_STREAM_COUNT: "True"
      TC_VC_STREAM_COUNT_CHANNEL_ID: 0
      TC_VC_TRANSCODE_COUNT: "False"
      TC_VC_TRANSCODE_COUNT_CHANNEL_ID: 0
      TC_VC_BANDWIDTH: "False"
      TC_VC_BANDWIDTH_CHANNEL_ID: 0
      TC_VC_LOCAL_BANDWIDTH: "False"
      TC_VC_LOCAL_BANDWIDTH_CHANNEL_ID: 0
      TC_VC_REMOTE_BANDWIDTH: "False"
      TC_VC_REMOTE_BANDWIDTH_CHANNEL_ID: 0
      TC_VC_PLEX_STATUS: "True"
      TC_VC_PLEX_STATUS_CHANNEL_ID: 0
      TC_VC_LIBRARIES_CATEGORY_NAME: "Library Stats"
      TC_VC_LIBRARY_STATS: "True"
      TC_VC_LIBRARY_NAMES: "Movies,TV Shows"
      TC_VC_LIBRARY_REFRESH_SECONDS: 3600
      TC_VC_LIBRARY_USE_EMOJIS: "True"
      TC_VC_TV_SERIES_COUNT: "True"
      TC_VC_TV_EPISODE_COUNT: "True"
      TC_VC_MUSIC_ARTIST_COUNT: "True"
      TC_VC_MUSIC_TRACK_COUNT: "True"
      TC_DISCORD_ADMIN_IDS: ********
      TC_DISCORD_POST_SUMMARY_MESSAGE: "True"
      TC_DISCORD_CHANNEL_NAME: "Library stats"
      TC_DISCORD_NITRO: "False"
      TC_ALLOW_ANALYTICS: "True"
      TC_VC_PERFORMANCE_CATEGORY_NAME: "Performance"
      TC_MONITOR_CPU: "True"
      TC_MONITOR_MEMORY: "True"
      TZ: America/Los_Angeles

```

Seems like a permission issue from looking at logs:

![image](https://github.com/nwithan8/tauticord/assets/1291968/86487188-e26b-406e-9e04-9634c6f41d05)

But I think my permissions are set correctly..?

![image](https://github.com/nwithan8/tauticord/assets/1291968/85b2b6c8-34e8-4317-ad7d-1167c875c9a7)
