### ISSUE TITLE
Tauticord logs have incorrect timezone

### ISSUE THREAD

**Issue by leddie24** [nwithan8/tauticord#141]
![image](https://github.com/nwithan8/tauticord/assets/1291968/9621909d-c932-4554-83ba-ab9149e41fa6)

Current time is 11:06 AM

My TZ is set to `America/Los_Angeles`

```
version: "3.9"
services:
  tauticord:
    image: nwithan8/tauticord:latest
    volumes:
      - ./config:/config
      - ./logs:/logs
    environment:
      TC_DISCORD_BOT_TOKEN: **hidden**
      TC_DISCORD_SERVER_ID: **hidden**
      TC_TAUTULLI_KEY: **hidden**
      TC_TAUTULLI_URL: http://192.168.68.72:8181/
      TC_USE_SELF_SIGNED_CERT: "False"
      TC_REFRESH_SECONDS: 15
      TC_TERMINATE_MESSAGE: "Your stream has ended."
      TC_SERVER_NAME: "Weird Plex But OK"
      TC_USE_24_HOUR_TIME: "False"
      TC_HIDE_USERNAMES: "True"
      TC_HIDE_PLATFORMS: "False"
      TC_HIDE_PLAYER_NAMES: "False"
      TC_HIDE_QUALITY: "False"
      TC_HIDE_BANDWIDTH: "False"
      TC_HIDE_TRANSCODE: "False"
      TC_HIDE_PROGRESS: "False"
      TC_HIDE_ETA: "False"
      TC_USE_FRIENDLY_NAMES: "False"
      TC_THOUSANDS_SEPARATOR: ""
      TC_VC_STATS_CATEGORY_NAME: "Plex Stream Stats"
      TC_VC_STREAM_COUNT: "True"
      TC_VC_STREAM_COUNT_CHANNEL_ID: 0
      TC_VC_TRANSCODE_COUNT: "False"
      TC_VC_TRANSCODE_COUNT_CHANNEL_ID: 0
      TC_VC_BANDWIDTH: "False"
      TC_VC_BANDWIDTH_CHANNEL_ID: 0
      TC_VC_LOCAL_BANDWIDTH: "False"
      TC_VC_LOCAL_BANDWIDTH_CHANNEL_ID: 0
      TC_VC_REMOTE_BANDWIDTH: "False"
      TC_VC_REMOTE_BANDWIDTH_CHANNEL_ID: 0
      TC_VC_PLEX_STATUS: "True"
      TC_VC_PLEX_STATUS_CHANNEL_ID: 0
      TC_VC_LIBRARIES_CATEGORY_NAME: "Library Stats"
      TC_VC_LIBRARY_STATS: "True"
      TC_VC_LIBRARY_NAMES: "Movies,TV Shows"
      TC_VC_LIBRARY_REFRESH_SECONDS: 3600
      TC_VC_LIBRARY_USE_EMOJIS: "True"
      TC_VC_TV_SERIES_COUNT: "True"
      TC_VC_TV_EPISODE_COUNT: "True"
      TC_VC_MUSIC_ARTIST_COUNT: "True"
      TC_VC_MUSIC_TRACK_COUNT: "True"
      TC_DISCORD_ADMIN_IDS: 200088560680960000
      TC_DISCORD_POST_SUMMARY_MESSAGE: "True"
      TC_DISCORD_CHANNEL_NAME: "Now Playing"
      TC_DISCORD_NITRO: "False"
      TC_ALLOW_ANALYTICS: "True"
      TC_VC_PERFORMANCE_CATEGORY_NAME: "Performance"
      TC_MONITOR_CPU: "True"
      TC_MONITOR_MEMORY: "True"
      TZ: America/Los_Angeles
```
